version: '3.8'

services:
  app:
    build: .
    container_name: ManageSchedules
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./tasks.db:/app/tasks.db
    # command: exec /app/run